//
// Created by marek on 5/16/25.
//

#ifndef ALFACAD_O_OFFSET_H
#define ALFACAD_O_OFFSET_H

enum OFFSET_MODE { POINT_OFFSET_MODE, DIST_OFFSET_MODE, SET_DIST_OFFSET, SET_OFFSET_STYLE, SET_OFFSET_NORMAL, SET_OFFSET_SMOOTH,
} ;
#endif //ALFACAD_O_OFFSET_H
